[2022-07-28 15:09:22,380] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: AAPL_historic_data.create_historic_table scheduled__2022-07-28T14:30:00+00:00 [queued]>
[2022-07-28 15:09:22,389] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: AAPL_historic_data.create_historic_table scheduled__2022-07-28T14:30:00+00:00 [queued]>
[2022-07-28 15:09:22,390] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 15:09:22,392] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-28 15:09:22,392] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 15:09:22,406] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_historic_table> on 2022-07-28 14:30:00+00:00
[2022-07-28 15:09:22,410] {standard_task_runner.py:52} INFO - Started process 725 to run task
[2022-07-28 15:09:22,414] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'AAPL_historic_data', 'create_historic_table', 'scheduled__2022-07-28T14:30:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmp9ygmj27r', '--error-file', '/tmp/tmptumdp3oz']
[2022-07-28 15:09:22,415] {standard_task_runner.py:80} INFO - Job 77: Subtask create_historic_table
[2022-07-28 15:09:22,489] {task_command.py:371} INFO - Running <TaskInstance: AAPL_historic_data.create_historic_table scheduled__2022-07-28T14:30:00+00:00 [running]> on host a2299eb83309
[2022-07-28 15:09:22,587] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=AAPL_historic_data
AIRFLOW_CTX_TASK_ID=create_historic_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T14:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-28T14:30:00+00:00
[2022-07-28 15:09:22,599] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-28 15:09:22,603] {dbapi.py:231} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS historic__AAPL_ (
            datetime BIGINT,
            high DOUBLE PRECISION,
            low DOUBLE PRECISION,
            open DOUBLE PRECISION,
            close DOUBLE PRECISION,
            volume INTEGER,
            symbol VARCHAR(32) NOT NULL,
            PRIMARY KEY (symbol, datetime)
        )
    , parameters: None
[2022-07-28 15:09:22,611] {python.py:173} INFO - Done. Returned value was: None
[2022-07-28 15:09:22,623] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=AAPL_historic_data, task_id=create_historic_table, execution_date=20220728T143000, start_date=20220728T150922, end_date=20220728T150922
[2022-07-28 15:09:22,666] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 15:09:22,939] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
